/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yass;

import actions.WorkingDays_Add;
import java.awt.event.ItemEvent;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author yass
 */
public final class add_working_days extends javax.swing.JFrame {

            WorkingDays_Add wa=new WorkingDays_Add();
    /**
     * Creates new form add_working_days
     */
    public add_working_days() {
        initComponents();

        //call Spinner Minus Stop
        spinnerMinusStop();
        
        //call Max Window size hidden
        maxsizehidden();
    }
void maxsizehidden(){
        setSize(1400, 820);
        setLocationRelativeTo(null);
        setResizable(false); // maximize button disable
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddWorkingDaysClick = new javax.swing.JButton();
        ManageWorkingDaysButtin = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerWorkingdays = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerHours = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jSpinnerMini = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jCheckBoxMon = new javax.swing.JCheckBox();
        ie = new javax.swing.JCheckBox();
        jCheckBoxWen = new javax.swing.JCheckBox();
        jCheckBoxThu = new javax.swing.JCheckBox();
        jCheckBoxFri = new javax.swing.JCheckBox();
        jCheckBoxSat = new javax.swing.JCheckBox();
        jCheckBoxSun = new javax.swing.JCheckBox();
        DashBoardClick = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasindu_img/logo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Add Working Days And Hours");

        AddWorkingDaysClick.setBackground(new java.awt.Color(0, 153, 153));
        AddWorkingDaysClick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddWorkingDaysClick.setText("Add Working Days");
        AddWorkingDaysClick.setPreferredSize(new java.awt.Dimension(175, 30));

        ManageWorkingDaysButtin.setBackground(new java.awt.Color(0, 153, 153));
        ManageWorkingDaysButtin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageWorkingDaysButtin.setText("Manage Working Days");
        ManageWorkingDaysButtin.setPreferredSize(new java.awt.Dimension(275, 30));
        ManageWorkingDaysButtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageWorkingDaysButtinActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(0, 153, 153));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BackButton.setText("<<BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("No.of Working Days");

        jSpinnerWorkingdays.setDoubleBuffered(true);
        jSpinnerWorkingdays.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Working Days");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Working Time Per Day");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("H");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 102, 102));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("M");

        jButtonSubmit.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(0, 153, 153));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jCheckBoxMon.setText("Monday");
        jCheckBoxMon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllCount(evt);
            }
        });
        jCheckBoxMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMonActionPerformed(evt);
            }
        });

        ie.setText("Tuesday");
        ie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllCount(evt);
            }
        });
        ie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ieActionPerformed(evt);
            }
        });

        jCheckBoxWen.setText("Wednesday");
        jCheckBoxWen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllCount(evt);
            }
        });
        jCheckBoxWen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWenActionPerformed(evt);
            }
        });

        jCheckBoxThu.setText("Thursday");
        jCheckBoxThu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllCount(evt);
            }
        });
        jCheckBoxThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThuActionPerformed(evt);
            }
        });

        jCheckBoxFri.setText("Friday");
        jCheckBoxFri.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllCount(evt);
            }
        });
        jCheckBoxFri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFriActionPerformed(evt);
            }
        });

        jCheckBoxSat.setText("Saturday");
        jCheckBoxSat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllCount(evt);
            }
        });
        jCheckBoxSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSatActionPerformed(evt);
                AllCheckCount(evt);
            }
        });

        jCheckBoxSun.setText("Sunday");
        jCheckBoxSun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllCount(evt);
            }
        });
        jCheckBoxSun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSpinnerMini, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSpinnerHours, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(50, 50, 50)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinnerWorkingdays, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jCheckBoxMon)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                            .addComponent(ie)
                                            .addGap(29, 29, 29))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jCheckBoxSat)
                                            .addGap(18, 18, 18)
                                            .addComponent(jCheckBoxSun)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jCheckBoxWen)
                                    .addGap(32, 32, 32)
                                    .addComponent(jCheckBoxThu)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBoxFri)
                                    .addGap(24, 24, 24))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerWorkingdays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxMon)
                            .addComponent(ie)
                            .addComponent(jCheckBoxWen)
                            .addComponent(jCheckBoxThu)
                            .addComponent(jCheckBoxFri))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxSat)
                            .addComponent(jCheckBoxSun))))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );

        DashBoardClick.setBackground(new java.awt.Color(0, 153, 153));
        DashBoardClick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DashBoardClick.setText("Dashboard");
        DashBoardClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashBoardClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(BackButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageWorkingDaysButtin, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(AddWorkingDaysClick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DashBoardClick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DashBoardClick, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(AddWorkingDaysClick, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(ManageWorkingDaysButtin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageWorkingDaysButtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageWorkingDaysButtinActionPerformed
        // TODO add your handling code here:
        manage_working_days mwd = new manage_working_days();
        mwd.show();
        dispose();
    }//GEN-LAST:event_ManageWorkingDaysButtinActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        manage_working_days da =new manage_working_days();
        da.show();
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jCheckBoxSunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSunActionPerformed
        // TODO add your handling code here:
        day7="Open";
    }//GEN-LAST:event_jCheckBoxSunActionPerformed

    private void jCheckBoxFriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFriActionPerformed
        // TODO add your handling code here:
        day5="Open";
    }//GEN-LAST:event_jCheckBoxFriActionPerformed

    private void jCheckBoxThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThuActionPerformed
        // TODO add your handling code here:
        day2="Open";
    }//GEN-LAST:event_jCheckBoxThuActionPerformed

    private void jCheckBoxWenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWenActionPerformed
        // TODO add your handling code here:
        day3="Open";
    }//GEN-LAST:event_jCheckBoxWenActionPerformed

    private void ieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ieActionPerformed
        // TODO add your handling code here:
        day4="Open";
    }//GEN-LAST:event_ieActionPerformed

    private void jCheckBoxMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMonActionPerformed
        // TODO add your handling code here:
        day1="Open";
    }//GEN-LAST:event_jCheckBoxMonActionPerformed

    
//Clear All the Feileds And Messages    
    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        
        jCheckBoxMon.setSelected(false);
        ie.setSelected(false);
        jCheckBoxWen.setSelected(false);
        jCheckBoxThu.setSelected(false);
        jCheckBoxFri.setSelected(false);
        jCheckBoxSat.setSelected(false);
        jCheckBoxSun.setSelected(false);
        jSpinnerWorkingdays.setValue(0);
        jSpinnerHours.setValue(0);
        jSpinnerMini.setValue(0);
    }//GEN-LAST:event_jButtonClearActionPerformed
  
    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
       
            String WorkingDays=jSpinnerWorkingdays.getValue().toString();
            
            //Call check Open or Close Vaildation
            openCloseValidation();
            
            String Day1=day1;
            String Day2=day2;
            String Day3=day3;
            String Day4=day4;
            String Day5=day5;
            String Day6=day6;
            String Day7=day7;
            String WorkingTimeHr=jSpinnerHours.getValue().toString();
            String WorkingTimeMin=jSpinnerMini.getValue().toString();
         
                
             wa.SaveWorkingDays(WorkingDays, Day1, Day2, Day3, Day4, Day5, Day6, Day7, WorkingTimeHr, WorkingTimeMin);
            

      
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jCheckBoxSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSatActionPerformed
        
        day6="Open";
    }//GEN-LAST:event_jCheckBoxSatActionPerformed

    private void AllCheckCount(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllCheckCount
   
    }//GEN-LAST:event_AllCheckCount

//Check Box Click to increase and discrese Counter mothode
    private void AllCount(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AllCount

       if(evt.getSource().getClass() == JCheckBox.class)
    {
        if(evt.getStateChange() == ItemEvent.SELECTED){
            countChecked++;
                jSpinnerWorkingdays.setValue(countChecked);

        
        } else if(evt.getStateChange() == ItemEvent.DESELECTED)
            countChecked--;
                jSpinnerWorkingdays.setValue(countChecked);
    }



    }//GEN-LAST:event_AllCount

          private  int countChecked = 0;

    
    private void DashBoardClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBoardClickActionPerformed
        // TODO add your handling code here:
      
        group_implmentation.loging.dashb.setVisible(true);
        this.dispose();
               
    }//GEN-LAST:event_DashBoardClickActionPerformed

//Mehode Spinner Minus Value Stop
  void spinnerMinusStop(){
   
          ((SpinnerNumberModel) jSpinnerHours.getModel()).setMinimum(0);
          ((SpinnerNumberModel) jSpinnerMini.getModel()).setMinimum(0);
   
  }

//Check Box Select Open or Close Vaildation     
void openCloseValidation(){
    if( jCheckBoxMon.isSelected()){
             
                day1="Open";

            }
            else {
             
                day1="Close";
            } 
    if(ie.isSelected()){
                
                day2="Open";
            
            }
            else{
            
                day2="Close";
            }
   
    if(jCheckBoxWen.isSelected()){
           
                day3="Open";
           }
           else{
           
                day3="Close";
           }
    if(jCheckBoxThu.isSelected()){
           
                day4="Open";
           }
           else{
           
                day4="Close";
           } 
    if(jCheckBoxFri.isSelected()){
           
                day5="Open";
           }
           else{
           
                day5="Close";
           }
   if(jCheckBoxSat.isSelected()){
           
                day6="Open";
           }
           else{
           
                day6="Close";
           }
   if(jCheckBoxSun.isSelected()){
           
                day7="Open";
           }
           else{
           
                day7="Close";
           }
   
   } 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_working_days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_working_days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_working_days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_working_days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_working_days().setVisible(true);
            }
        });
    }

    String day1,day2,day3,day4,day5,day6,day7;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddWorkingDaysClick;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DashBoardClick;
    private javax.swing.JButton ManageWorkingDaysButtin;
    private javax.swing.JCheckBox ie;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JCheckBox jCheckBoxFri;
    private javax.swing.JCheckBox jCheckBoxMon;
    private javax.swing.JCheckBox jCheckBoxSat;
    private javax.swing.JCheckBox jCheckBoxSun;
    private javax.swing.JCheckBox jCheckBoxThu;
    private javax.swing.JCheckBox jCheckBoxWen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerHours;
    private javax.swing.JSpinner jSpinnerMini;
    private javax.swing.JSpinner jSpinnerWorkingdays;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
