/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasindu;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import madu.Add_Lecturer;

/**
 *
 * @author pasindu
 */
public final class Add_SessionRoom extends javax.swing.JFrame {

    /**
     * Creates new form Add_SessionRoom
     */
    public Add_SessionRoom() {
        initComponents();
        //implement the hide size function
        hidesize();

        Roomcombox();

    }

    //hidden Window size and hide maximize   
    void hidesize() {

        setSize(1400, 820);
        setLocationRelativeTo(null);
        setResizable(false); // maximize button disable
        

    }
//Retrive Rooms Combox
    void Roomcombox() {
     
        try {
            Connection cn = connection.DB_Connect.ConnecrDB();

            String sql = "select DISTINCT room_name from location";
            Statement pst = cn.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {

                String name = rs.getString("room_name");
                jComboBoxRoom.addItem(name);

            }
            //Connection Close
            pst.close();
            rs.close();
            cn.close();

        } catch (SQLException ex) {
            Logger.getLogger(Add_Lecturer.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxRoom = new javax.swing.JComboBox<>();
        jButtonSubmit = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxSessonType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonView1 = new javax.swing.JButton();
        jButtonView2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ManageSessionRommClick = new javax.swing.JButton();
        BackClick = new javax.swing.JButton();
        DashboardClike = new javax.swing.JButton();
        SessionRoomClicked = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 820));

        jLabel1.setBackground(new java.awt.Color(204, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasindu_img/logo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel2.setPreferredSize(new java.awt.Dimension(870, 646));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Select Section:-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Select Room");

        jComboBoxRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBoxRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoomActionPerformed(evt);
            }
        });

        jButtonSubmit.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(0, 153, 153));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Select Session");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Selected Session:");

        jComboBoxSessonType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consecutive", "Parallel", "Non-Overlapping" }));
        jComboBoxSessonType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSessonTypeActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jButtonView.setBackground(new java.awt.Color(255, 204, 0));
        jButtonView.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList2);

        jButtonView1.setBackground(new java.awt.Color(0, 204, 51));
        jButtonView1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonView1.setText("Add");
        jButtonView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonView1ActionPerformed(evt);
            }
        });

        jButtonView2.setBackground(new java.awt.Color(204, 51, 0));
        jButtonView2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonView2.setText("Remove selected");
        jButtonView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonView2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonView2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBoxSessonType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonView, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                                    .addComponent(jComboBoxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSessonType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonView1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonView2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxRoom)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Add Session Rooms");

        ManageSessionRommClick.setBackground(new java.awt.Color(0, 153, 153));
        ManageSessionRommClick.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManageSessionRommClick.setText("View Session Rooms");
        ManageSessionRommClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSessionRommClickActionPerformed(evt);
            }
        });

        BackClick.setBackground(new java.awt.Color(0, 153, 153));
        BackClick.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackClick.setText("<<Back");
        BackClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackClickActionPerformed(evt);
            }
        });

        DashboardClike.setBackground(new java.awt.Color(0, 153, 153));
        DashboardClike.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DashboardClike.setText("Dashboard");
        DashboardClike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardClikeActionPerformed(evt);
            }
        });

        SessionRoomClicked.setBackground(new java.awt.Color(0, 153, 153));
        SessionRoomClicked.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SessionRoomClicked.setText("Add Session Rooms");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SessionRoomClicked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DashboardClike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ManageSessionRommClick, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(BackClick, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DashboardClike, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(SessionRoomClicked, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ManageSessionRommClick, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BackClick, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
View_SessionRoom al4;
    private void BackClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackClickActionPerformed

          if (al4 == null) {
            al4 = new View_SessionRoom();
        }
        
        al4.setVisible(true);
        this.dispose();
       


    }//GEN-LAST:event_BackClickActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:

        String ch = jComboBoxSessonType.getSelectedItem().toString();

        if ("Consecutive".equals(ch) || "Parallel".equals(ch) || "Non-Overlapping".equals(ch)) {
            try {

                for (int i = 0; i < jList2.getModel().getSize(); i++) {

                    try (Connection cn = connection.DB_Connect.ConnecrDB()) {
                        String val = jList2.getModel().getElementAt(i);
                        String update = "UPDATE session SET roomname = ? WHERE sesname= ? ";
                        
                        PreparedStatement pst = cn.prepareStatement(update);
                        String room = jComboBoxRoom.getSelectedItem().toString();
                        
                        pst.setString(1, room);
                        pst.setString(2, val);
                        
                    if(jComboBoxRoom.getSelectedIndex()==0){
                    
                            JOptionPane.showMessageDialog(this, "Please Select Room");

                    }else{  
                        
                        pst.execute();
                        
                        pst.close();
                    }    
                    }
                }

            } catch (HeadlessException | SQLException e) {
//call NOTNULL validation 
                JOptionPane.showMessageDialog(this, e);
            }

        }if(jComboBoxRoom.getSelectedIndex() !=0){
        
            JOptionPane.showMessageDialog(this, "Added Sucess");
        }

    }//GEN-LAST:event_jButtonSubmitActionPerformed
Add_SessionRoom al2;
    private void jComboBoxRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoomActionPerformed

    private void DashboardClikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardClikeActionPerformed
        // TODO add your handling code here:
   
        group_implmentation.loging.dashb.setVisible(true);
        this.dispose();  

    }//GEN-LAST:event_DashboardClikeActionPerformed
View_SessionRoom al3;
    private void ManageSessionRommClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSessionRommClickActionPerformed
        // TODO add your handling code here:
         if (al3 == null) {
            al3 = new View_SessionRoom();
        }
        
        al3.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_ManageSessionRommClickActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        // TODO add your handling code here:

        String ch = jComboBoxSessonType.getSelectedItem().toString();

        if ("Consecutive".equals(ch)) {

            try {
                try (Connection cn = connection.DB_Connect.ConnecrDB()) {
                    DefaultListModel DML = new DefaultListModel();
                    String sql = "select DISTINCT sesname from consecutive";
                    Statement pst = cn.createStatement();

                    ResultSet rs = pst.executeQuery(sql);

                    while (rs.next()) {

                        String sesname = rs.getString("sesname");

                        // String group=rs.getString("lec1");
                        DML.addElement(sesname);

                        jList1.setModel(DML);

                    }

                    try {
                        DefaultListModel df = (DefaultListModel) jList2.getModel();
                        df.removeAllElements();
                    } catch (Exception e) {
                    }
                    //Connection Close
                    pst.close();
                    rs.close();

                }

            } catch (SQLException ex) {
                Logger.getLogger(Add_Lecturer.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            //, Parallel, 
        } else if ("Parallel".equals(ch)) {

            try {
                try (Connection cn = connection.DB_Connect.ConnecrDB()) {
                    DefaultListModel DML = new DefaultListModel();
                    String sql = "select DISTINCT sesname from parallel";
                    ResultSet rs;
                    try (Statement pst = cn.createStatement()) {
                        rs = pst.executeQuery(sql);
                        while (rs.next()) {
                            String sesname = rs.getString("sesname");
                            
                            // String group=rs.getString("lec1");
                            DML.addElement(sesname);
                            
                            jList1.setModel(DML);
                        }
                        //Connection Close
                    }
                    rs.close();

                }

            } catch (SQLException ex) {
                Logger.getLogger(Add_Lecturer.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }

        } else if ("Non-Overlapping".equals(ch)) {

            try {
                try (Connection cn = connection.DB_Connect.ConnecrDB()) {
                    DefaultListModel DML = new DefaultListModel();
                    String sql = "select DISTINCT sesname from non_overlapping";
                    ResultSet rs;
                    try (Statement pst = cn.createStatement()) {
                        rs = pst.executeQuery(sql);
                        while (rs.next()) {
                            String sesname = rs.getString("sesname");
                            
                            // String group=rs.getString("lec1");
                            DML.addElement(sesname);
                            
                            jList1.setModel(DML);
                        }
                        //Connection Close
                    }
                    rs.close();

                }

            } catch (SQLException ex) {
                Logger.getLogger(Add_Lecturer.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }

        }


    }//GEN-LAST:event_jButtonViewActionPerformed
    DefaultListModel m = new DefaultListModel();

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked


    }//GEN-LAST:event_jList1MouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        m.clear();
        jList1.setModel(m);
        jComboBoxSessonType.setSelectedIndex(0);
        jComboBoxRoom.setSelectedIndex(0);

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonView1ActionPerformed

        // TODO add your handling code here:
        String data = jList1.getSelectedValue();

        m.addElement(data);

        jList2.setModel(m);

        DefaultListModel df = (DefaultListModel) jList1.getModel();

        df.remove(jList1.getSelectedIndex());

    }//GEN-LAST:event_jButtonView1ActionPerformed

    private void jButtonView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonView2ActionPerformed

        DefaultListModel df = (DefaultListModel) jList2.getModel();
        DefaultListModel df1 = (DefaultListModel) jList1.getModel();

        if (JOptionPane.showConfirmDialog(this, "Are you sure to remove selected row ?") == 0) {

            String data = jList2.getSelectedValue();

            df1.addElement(data);

            int i = jList2.getSelectedIndex();

            df.remove(i);
        }


    }//GEN-LAST:event_jButtonView2ActionPerformed

    private void jComboBoxSessonTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSessonTypeActionPerformed

        try {
            DefaultListModel df1 = (DefaultListModel) jList1.getModel();
            df1.removeAllElements();
            DefaultListModel df = (DefaultListModel) jList2.getModel();
            df.removeAllElements();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jComboBoxSessonTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_SessionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_SessionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_SessionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_SessionRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_SessionRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackClick;
    private javax.swing.JButton DashboardClike;
    private javax.swing.JButton ManageSessionRommClick;
    private javax.swing.JButton SessionRoomClicked;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonView;
    private javax.swing.JButton jButtonView1;
    private javax.swing.JButton jButtonView2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxRoom;
    private javax.swing.JComboBox<String> jComboBoxSessonType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
