/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package madu;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import actions.Subject_Add;

/**
 *
 * @author Madu
 */
public final class Add_Subject extends javax.swing.JFrame {
                Subject_Add sa=new Subject_Add();
    /**
     * Creates new form Add_Subject
     */
public Add_Subject() {
        initComponents();
//call the hide size function
        hidesize();

//call the Negative Num Spinner Stop        
        negativeSpinnerStop();         

}

//Set Window Size and Maxzimize hidden Window
void hidesize(){
  
      setSize(1400, 820);
      setLocationRelativeTo(null);
      setResizable(false); // maximize button disable
    
  }
//negative Numbers Stop Spinner 
void negativeSpinnerStop(){

          ((SpinnerNumberModel) jSpinnerLecturerHours.getModel()).setMinimum(0);
          ((SpinnerNumberModel) jSpinnerTutorialHours.getModel()).setMinimum(0);
          ((SpinnerNumberModel) jSpinnerEvalucationHours.getModel()).setMinimum(0);
          ((SpinnerNumberModel) jSpinnerLabHours.getModel()).setMinimum(0);
}

//system Validation for NOt Null Sql
 void validation(){
    if(jTextFieldSubjectName.getText().trim().isEmpty()){
             
        erroSubjectName.setText("Please Enter Subject Name");
         
    }
     
    else if(jTextFieldSubjectCode.getText().trim().isEmpty()){
              
        erroSubjectCode.setText("Please Enter Subject Code");

    }
     
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxOfferedYear = new javax.swing.JComboBox<>();
        jRadioButton1sem = new javax.swing.JRadioButton();
        jRadioButton2Sem = new javax.swing.JRadioButton();
        jTextFieldSubjectName = new javax.swing.JTextField();
        jTextFieldSubjectCode = new javax.swing.JTextField();
        jSpinnerLecturerHours = new javax.swing.JSpinner();
        jSpinnerTutorialHours = new javax.swing.JSpinner();
        jSpinnerLabHours = new javax.swing.JSpinner();
        jSpinnerEvalucationHours = new javax.swing.JSpinner();
        SaveSubjectClick = new javax.swing.JButton();
        ClearSubjectClick = new javax.swing.JButton();
        erroSelectYear = new javax.swing.JLabel();
        erroOfferedSemester = new javax.swing.JLabel();
        erroSubjectName = new javax.swing.JLabel();
        erroSubjectCode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClickDash = new javax.swing.JButton();
        AddSubjectClick = new javax.swing.JButton();
        ManageSubjectClick = new javax.swing.JButton();
        BackClick = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 820));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pasindu_img/logo.jpeg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Offered year");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Offered Semester");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Subject Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Subject code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Number of Lecturer Hours");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Number of Tutorial Hours");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Number of Lab Hours");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Number of Evalucation Hours");

        jComboBoxOfferedYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y1", "Y2", "Y3", "Y4", " " }));
        jComboBoxOfferedYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOfferedYearItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton1sem);
        jRadioButton1sem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1sem.setText("1 st Semester");
        jRadioButton1sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1semActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2Sem);
        jRadioButton2Sem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2Sem.setText("2 nd Semester");
        jRadioButton2Sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2SemActionPerformed(evt);
            }
        });

        jTextFieldSubjectName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSubjectNameKeyReleased(evt);
            }
        });

        jTextFieldSubjectCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSubjectCodeKeyReleased(evt);
            }
        });

        jSpinnerLecturerHours.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerLecturerHours.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinnerLecturerHours.setDoubleBuffered(true);
        jSpinnerLecturerHours.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerLecturerHours, ""));
        jSpinnerLecturerHours.setFocusCycleRoot(true);

        jSpinnerTutorialHours.setModel(new javax.swing.SpinnerNumberModel());

        jSpinnerLabHours.setModel(new javax.swing.SpinnerNumberModel());

        jSpinnerEvalucationHours.setModel(new javax.swing.SpinnerNumberModel());

        SaveSubjectClick.setBackground(new java.awt.Color(0, 153, 153));
        SaveSubjectClick.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveSubjectClick.setText("Save");
        SaveSubjectClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveSubjectClickActionPerformed(evt);
            }
        });

        ClearSubjectClick.setBackground(new java.awt.Color(0, 153, 153));
        ClearSubjectClick.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearSubjectClick.setText("Clear");
        ClearSubjectClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearSubjectClickActionPerformed(evt);
            }
        });

        erroSelectYear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        erroSelectYear.setForeground(java.awt.Color.red);

        erroOfferedSemester.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        erroOfferedSemester.setForeground(java.awt.Color.red);

        erroSubjectName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        erroSubjectName.setForeground(java.awt.Color.red);

        erroSubjectCode.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        erroSubjectCode.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearSubjectClick, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaveSubjectClick, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(erroSelectYear, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(54, 54, 54)
                                    .addComponent(jComboBoxOfferedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldSubjectName)
                                            .addComponent(jTextFieldSubjectCode)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1sem)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton2Sem)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(erroOfferedSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(erroSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erroSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerLecturerHours, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerTutorialHours)
                    .addComponent(jSpinnerLabHours)
                    .addComponent(jSpinnerEvalucationHours))
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxOfferedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerLecturerHours, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroSelectYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1sem)
                    .addComponent(jRadioButton2Sem)
                    .addComponent(jSpinnerTutorialHours, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroOfferedSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9)
                        .addComponent(jTextFieldSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerLabHours, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerEvalucationHours, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SaveSubjectClick, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(ClearSubjectClick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Add Subject");

        ClickDash.setBackground(new java.awt.Color(0, 153, 153));
        ClickDash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClickDash.setText("Dashboard");
        ClickDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickDashActionPerformed(evt);
            }
        });

        AddSubjectClick.setBackground(new java.awt.Color(0, 153, 153));
        AddSubjectClick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddSubjectClick.setText("Add Subject");

        ManageSubjectClick.setBackground(new java.awt.Color(0, 153, 153));
        ManageSubjectClick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManageSubjectClick.setText("Manage Subject");
        ManageSubjectClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSubjectClickActionPerformed(evt);
            }
        });

        BackClick.setBackground(new java.awt.Color(0, 153, 153));
        BackClick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackClick.setText("<<Back");
        BackClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ManageSubjectClick, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(AddSubjectClick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClickDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(BackClick, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClickDash, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(AddSubjectClick, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ManageSubjectClick, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BackClick, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
//Insert Subject Data Table
    private void SaveSubjectClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveSubjectClickActionPerformed
         
           String SubjectCode=jTextFieldSubjectCode.getText();
           String SubjectName=jTextFieldSubjectName.getText();
           String OfferedYear=jComboBoxOfferedYear.getSelectedItem().toString();
            if(jRadioButton1sem.isSelected()){
                    semester="1-Semester";
            
                }
                if(jRadioButton2Sem.isSelected()){
                    semester="2-Semester";
                }
           String Semester=semester;
           String EvalucationHours=jSpinnerEvalucationHours.getValue().toString();
           String LabHours=jSpinnerLabHours.getValue().toString();
           String TutorialHours=jSpinnerTutorialHours.getValue().toString();
           String LecturerHours=jSpinnerLecturerHours.getValue().toString();

//This validation is applicable when semester is true.
        if(!("1-Semester".equals(semester)|| "2-Semester".equals(semester)) || jTextFieldSubjectName.getText().trim().isEmpty() || jTextFieldSubjectCode.getText().trim().isEmpty()){
            
 JOptionPane.showMessageDialog(null, "Some Feilds Are Empty");             
        }
               
        else{
            
              sa.Add_Subject(SubjectCode, SubjectName, OfferedYear, Semester, EvalucationHours, LabHours, TutorialHours, LecturerHours);

          }
         
        
    }//GEN-LAST:event_SaveSubjectClickActionPerformed

    private void jRadioButton1semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1semActionPerformed
        // TODO add your handling code here:
        semester ="1-Semester";
    }//GEN-LAST:event_jRadioButton1semActionPerformed

    private void jRadioButton2SemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2SemActionPerformed
        // TODO add your handling code here:
        semester="2-Semester";
    }//GEN-LAST:event_jRadioButton2SemActionPerformed

//clear all the feilds and labels
    private void ClearSubjectClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearSubjectClickActionPerformed
        // TODO add your handling code here:
            
        jTextFieldSubjectName.setText("");
        jTextFieldSubjectCode.setText("");
        buttonGroup1.clearSelection();
        jSpinnerTutorialHours.setValue(0);
        jSpinnerLabHours.setValue(0);
        jSpinnerLecturerHours.setValue(0);
        jSpinnerEvalucationHours.setValue(0);
        jComboBoxOfferedYear.setSelectedIndex(0);
        erroSubjectName.setText("");
        erroSubjectCode.setText("");
        erroSelectYear.setText("");
        erroOfferedSemester.setText("");
    }//GEN-LAST:event_ClearSubjectClickActionPerformed
//Reset vaildtion called
    private void jTextFieldSubjectNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSubjectNameKeyReleased
        // TODO add your handling code here:
        erroSubjectName.setText(null);
    }//GEN-LAST:event_jTextFieldSubjectNameKeyReleased

    private void jTextFieldSubjectCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSubjectCodeKeyReleased
        // TODO add your handling code here:
        erroSubjectCode.setText(null);
    }//GEN-LAST:event_jTextFieldSubjectCodeKeyReleased

    private void jComboBoxOfferedYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOfferedYearItemStateChanged
        // TODO add your handling code here:

        erroSelectYear.setText(null);
    }//GEN-LAST:event_jComboBoxOfferedYearItemStateChanged

    private void ClickDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickDashActionPerformed
        // TODO add your handling code here:
       
        group_implmentation.loging.dashb.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ClickDashActionPerformed
Add_Subject as;Manage_Subject ms;
    private void ManageSubjectClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSubjectClickActionPerformed
        // TODO add your handling code here:
            if (ms == null) {
            ms = new Manage_Subject();
        }
        
        ms.setVisible(true);
        this.dispose();
      
        
    }//GEN-LAST:event_ManageSubjectClickActionPerformed

    private void BackClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackClickActionPerformed
        // TODO add your handling code here:
            if (ms == null) {
            ms = new Manage_Subject();
        }
        
        ms.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_BackClickActionPerformed

 
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Subject().setVisible(true);
            }

        });
    }

    public String semester;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSubjectClick;
    private javax.swing.JButton BackClick;
    private javax.swing.JButton ClearSubjectClick;
    private javax.swing.JButton ClickDash;
    private javax.swing.JButton ManageSubjectClick;
    private javax.swing.JButton SaveSubjectClick;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel erroOfferedSemester;
    private javax.swing.JLabel erroSelectYear;
    private javax.swing.JLabel erroSubjectCode;
    private javax.swing.JLabel erroSubjectName;
    private javax.swing.JComboBox<String> jComboBoxOfferedYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1sem;
    private javax.swing.JRadioButton jRadioButton2Sem;
    private javax.swing.JSpinner jSpinnerEvalucationHours;
    private javax.swing.JSpinner jSpinnerLabHours;
    private javax.swing.JSpinner jSpinnerLecturerHours;
    private javax.swing.JSpinner jSpinnerTutorialHours;
    private javax.swing.JTextField jTextFieldSubjectCode;
    private javax.swing.JTextField jTextFieldSubjectName;
    // End of variables declaration//GEN-END:variables
}
